apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-tp
  labels:
    app: deployment-tp
    tier: devops
spec:
  selector:
    matchLabels:
      app: deployment-tp
  replicas: 3
  template:
    metadata:
      labels:
        app: deployment-tp
    spec:
      containers:
        - name: deployment-tp
          image: dockercloud/hello-world
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
